// packages/ui-vue/src/components/LoadingSpinner.vue
<template>
  <div :class="['loading-spinner-container', { 'full-screen': fullScreen }]">
    <div :class="['loading-spinner', sizeClass, variantClass]">
      <div class="spinner" :style="spinnerStyle">
        <svg viewBox="0 0 50 50">
          <circle
            class="path"
            cx="25"
            cy="25"
            r="20"
            fill="none"
            :stroke-width="strokeWidth"
          />
        </svg>
      </div>
      <p v-if="message" class="loading-message">{{ message }}</p>
    </div>
  </div>
</template>

<script>
import { computed } from 'vue';

export default {
  name: 'LoadingSpinner',
  props: {
    size: {
      type: String,
      default: 'medium',
      validator: (value) => ['small', 'medium', 'large', 'xlarge'].includes(value)
    },
    color: {
      type: String,
      default: null
    },
    message: {
      type: String,
      default: null
    },
    fullScreen: {
      type: Boolean,
      default: false
    },
    variant: {
      type: String,
      default: 'primary',
      validator: (value) => ['primary', 'secondary', 'success', 'danger', 'warning', 'info'].includes(value)
    },
    strokeWidth: {
      type: Number,
      default: 3
    }
  },
  setup(props) {
    const sizeClass = computed(() => `size-${props.size}`);
    const variantClass = computed(() => `variant-${props.variant}`);
    
    const spinnerStyle = computed(() => {
      if (props.color) {
        return { '--spinner-color': props.color };
      }
      return {};
    });

    return {
      sizeClass,
      variantClass,
      spinnerStyle
    };
  }
};
</script>

<style scoped>
.loading-spinner-container {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 20px;
}

.loading-spinner-container.full-screen {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(255, 255, 255, 0.9);
  z-index: 9999;
}

.loading-spinner {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;
}

/* Size variants */
.loading-spinner.size-small .spinner {
  width: 24px;
  height: 24px;
}

.loading-spinner.size-medium .spinner {
  width: 40px;
  height: 40px;
}

.loading-spinner.size-large .spinner {
  width: 60px;
  height: 60px;
}

.loading-spinner.size-xlarge .spinner {
  width: 80px;
  height: 80px;
}

/* Color variants */
.loading-spinner.variant-primary {
  --spinner-color: #007bff;
}

.loading-spinner.variant-secondary {
  --spinner-color: #6c757d;
}

.loading-spinner.variant-success {
  --spinner-color: #28a745;
}

.loading-spinner.variant-danger {
  --spinner-color: #dc3545;
}

.loading-spinner.variant-warning {
  --spinner-color: #ffc107;
}

.loading-spinner.variant-info {
  --spinner-color: #17a2b8;
}

.spinner {
  animation: rotate 2s linear infinite;
}

.spinner svg {
  width: 100%;
  height: 100%;
}

.path {
  stroke: var(--spinner-color, #007bff);
  stroke-linecap: round;
  animation: dash 1.5s ease-in-out infinite;
}

.loading-message {
  margin: 0;
  color: #586069;
  font-size: 14px;
  text-align: center;
}

.loading-spinner.size-small .loading-message {
  font-size: 12px;
}

.loading-spinner.size-large .loading-message {
  font-size: 16px;
}

.loading-spinner.size-xlarge .loading-message {
  font-size: 18px;
}

@keyframes rotate {
  100% {
    transform: rotate(360deg);
  }
}

@keyframes dash {
  0% {
    stroke-dasharray: 1, 150;
    stroke-dashoffset: 0;
  }
  50% {
    stroke-dasharray: 90, 150;
    stroke-dashoffset: -35;
  }
  100% {
    stroke-dasharray: 90, 150;
    stroke-dashoffset: -124;
  }
}
</style>

// packages/ui/angular/src/components/loading/loading-spinner.component.ts
/**
 * Angular Loading Spinner Component
 * Displays a customizable loading spinner
 */

import { 
  Component, 
  Input,
  ChangeDetectionStrategy
} from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'frigg-loading-spinner',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div 
      class="frigg-loading-spinner"
      [class.frigg-loading-spinner--small]="size === 'small'"
      [class.frigg-loading-spinner--large]="size === 'large'"
      [class.frigg-loading-spinner--inline]="inline"
      [class.frigg-loading-spinner--overlay]="overlay"
    >
      <div class="frigg-loading-spinner__container" *ngIf="!overlay">
        <svg 
          class="frigg-loading-spinner__svg" 
          viewBox="0 0 24 24" 
          fill="none"
          [attr.aria-label]="label"
        >
          <circle 
            class="frigg-loading-spinner__circle-bg"
            cx="12" 
            cy="12" 
            r="10" 
            stroke="currentColor" 
            stroke-width="2"
          />
          <path 
            class="frigg-loading-spinner__circle"
            d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10"
            stroke="currentColor" 
            stroke-width="2"
            stroke-linecap="round"
          />
        </svg>
        <span class="frigg-loading-spinner__text" *ngIf="text">{{ text }}</span>
      </div>
      
      <div class="frigg-loading-spinner__overlay" *ngIf="overlay">
        <div class="frigg-loading-spinner__overlay-content">
          <svg 
            class="frigg-loading-spinner__svg" 
            viewBox="0 0 24 24" 
            fill="none"
            [attr.aria-label]="label"
          >
            <circle 
              class="frigg-loading-spinner__circle-bg"
              cx="12" 
              cy="12" 
              r="10" 
              stroke="currentColor" 
              stroke-width="2"
            />
            <path 
              class="frigg-loading-spinner__circle"
              d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10"
              stroke="currentColor" 
              stroke-width="2"
              stroke-linecap="round"
            />
          </svg>
          <span class="frigg-loading-spinner__text" *ngIf="text">{{ text }}</span>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .frigg-loading-spinner {
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .frigg-loading-spinner__container {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 8px;
    }

    .frigg-loading-spinner__svg {
      width: 32px;
      height: 32px;
      animation: spin 1s linear infinite;
      color: #3B82F6;
    }

    .frigg-loading-spinner--small .frigg-loading-spinner__svg {
      width: 20px;
      height: 20px;
    }

    .frigg-loading-spinner--large .frigg-loading-spinner__svg {
      width: 48px;
      height: 48px;
    }

    .frigg-loading-spinner__circle-bg {
      opacity: 0.2;
    }

    .frigg-loading-spinner__circle {
      opacity: 1;
    }

    .frigg-loading-spinner__text {
      font-size: 14px;
      color: #6B7280;
      text-align: center;
    }

    .frigg-loading-spinner--inline {
      display: inline-flex;
    }

    .frigg-loading-spinner--inline .frigg-loading-spinner__container {
      flex-direction: row;
    }

    /* Overlay styles */
    .frigg-loading-spinner--overlay {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      z-index: 9998;
    }

    .frigg-loading-spinner__overlay {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      display: flex;
      align-items: center;
      justify-content: center;
      background: rgba(255, 255, 255, 0.95);
      backdrop-filter: blur(4px);
    }

    .frigg-loading-spinner__overlay-content {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 12px;
    }

    /* Dark mode support */
    @media (prefers-color-scheme: dark) {
      .frigg-loading-spinner__svg {
        color: #60A5FA;
      }

      .frigg-loading-spinner__text {
        color: #D1D5DB;
      }

      .frigg-loading-spinner__overlay {
        background: rgba(17, 24, 39, 0.95);
      }
    }

    /* Animation */
    @keyframes spin {
      from {
        transform: rotate(0deg);
      }
      to {
        transform: rotate(360deg);
      }
    }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class FriggLoadingSpinnerComponent {
  @Input() size: 'small' | 'medium' | 'large' = 'medium';
  @Input() text?: string;
  @Input() inline: boolean = false;
  @Input() overlay: boolean = false;
  @Input() label: string = 'Loading';
}
