// packages/ui-svelte/src/components/LoadingSpinner.svelte
<script>
  import { fade } from 'svelte/transition';

  // Props
  export let size = 'md';
  export let color = 'primary';
  export let overlay = false;
  export let message = '';
  export let className = '';

  // Size mappings
  $: sizeClasses = {
    xs: 'w-3 h-3 border',
    sm: 'w-4 h-4 border',
    md: 'w-8 h-8 border-2',
    lg: 'w-12 h-12 border-2',
    xl: 'w-16 h-16 border-4'
  }[size] || 'w-8 h-8 border-2';

  // Color mappings
  $: colorClasses = {
    primary: 'border-blue-600 border-t-transparent',
    secondary: 'border-gray-600 border-t-transparent',
    success: 'border-green-600 border-t-transparent',
    danger: 'border-red-600 border-t-transparent',
    warning: 'border-yellow-600 border-t-transparent',
    white: 'border-white border-t-transparent',
    current: 'border-current border-t-transparent'
  }[color] || 'border-blue-600 border-t-transparent';
</script>

{#if overlay}
  <div 
    class="loading-overlay fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"
    transition:fade={{ duration: 200 }}
  >
    <div class="loading-content bg-white rounded-lg p-6 shadow-xl flex flex-col items-center gap-4">
      <div 
        class="spinner animate-spin rounded-full {sizeClasses} {colorClasses} {className}"
        role="status"
        aria-label="Loading"
      />
      {#if message}
        <p class="text-gray-700 text-sm font-medium">{message}</p>
      {/if}
    </div>
  </div>
{:else}
  <div class="inline-flex items-center gap-3">
    <div 
      class="spinner animate-spin rounded-full {sizeClasses} {colorClasses} {className}"
      role="status"
      aria-label="Loading"
    />
    {#if message}
      <span class="text-gray-700 text-sm">{message}</span>
    {/if}
  </div>
{/if}

<style>
  @keyframes spin {
    to { transform: rotate(360deg); }
  }

  .animate-spin {
    animation: spin 1s linear infinite;
  }

  .loading-overlay {
    backdrop-filter: blur(2px);
  }
</style>

// packages/devtools/management-ui/src/components/LoadingSpinner.jsx
import React from 'react'
import { cn } from '../lib/utils'
import { Loader2 } from 'lucide-react'

const LoadingSpinner = ({ size = 'md', className, variant = 'default', ...props }) => {
  const sizeMap = {
    sm: 16,
    md: 24,
    lg: 32,
    xl: 48
  }

  const variantClasses = {
    default: 'text-primary',
    secondary: 'text-secondary',
    muted: 'text-muted-foreground'
  }

  return (
    <Loader2
      size={sizeMap[size]}
      className={cn(
        'animate-spin',
        variantClasses[variant],
        className
      )}
      {...props}
    />
  )
}

// Full page loading spinner with industrial design
export const LoadingPage = ({ message = 'Loading...' }) => {
  return (
    <div className="flex flex-col items-center justify-center min-h-[400px] gap-4">
      <div className="relative">
        <div className="absolute inset-0 bg-primary/20 blur-xl rounded-full animate-pulse" />
        <LoadingSpinner size="xl" className="relative" />
      </div>
      <p className="text-sm text-muted-foreground font-medium">{message}</p>
    </div>
  )
}
export default LoadingSpinner
