// packages/ui-angular/src/components/modal/modal.component.ts
/**
 * Angular Modal Component
 * Displays content in a modal overlay with customizable options
 */

import { 
  Component, 
  Input, 
  Output, 
  EventEmitter,
  OnInit,
  OnDestroy,
  ChangeDetectionStrategy,
  ViewChild,
  ElementRef,
  AfterViewInit
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { 
  trigger, 
  state, 
  style, 
  transition, 
  animate 
} from '@angular/animations';

@Component({
  selector: 'frigg-modal',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div 
      class="frigg-modal"
      [class.frigg-modal--open]="isOpen"
      [@fadeIn]="isOpen ? 'visible' : 'hidden'"
      (click)="handleBackdropClick($event)"
    >
      <div 
        class="frigg-modal__backdrop"
        [@fadeIn]="isOpen ? 'visible' : 'hidden'"
      ></div>
      
      <div 
        class="frigg-modal__container"
        [class.frigg-modal__container--small]="size === 'small'"
        [class.frigg-modal__container--large]="size === 'large'"
        [class.frigg-modal__container--fullscreen]="size === 'fullscreen'"
        [@slideUp]="isOpen ? 'visible' : 'hidden'"
        #modalContent
      >
        <div class="frigg-modal__header" *ngIf="title || showCloseButton">
          <h2 class="frigg-modal__title" *ngIf="title">{{ title }}</h2>
          <button 
            *ngIf="showCloseButton"
            class="frigg-modal__close"
            (click)="handleClose()"
            aria-label="Close modal"
          >
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        
        <div class="frigg-modal__body">
          <ng-content></ng-content>
        </div>
        
        <div class="frigg-modal__footer" *ngIf="showFooter">
          <ng-content select="[modal-footer]"></ng-content>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .frigg-modal {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      z-index: 10000;
      display: none;
      align-items: center;
      justify-content: center;
      padding: 20px;
    }

    .frigg-modal--open {
      display: flex;
    }

    .frigg-modal__backdrop {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background: rgba(0, 0, 0, 0.5);
      backdrop-filter: blur(4px);
    }

    .frigg-modal__container {
      position: relative;
      max-width: 600px;
      width: 100%;
      max-height: 90vh;
      display: flex;
      flex-direction: column;
      background: white;
      border-radius: 12px;
      box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
      overflow: hidden;
    }

    .frigg-modal__container--small {
      max-width: 400px;
    }

    .frigg-modal__container--large {
      max-width: 800px;
    }

    .frigg-modal__container--fullscreen {
      max-width: 100%;
      width: 100%;
      height: 100vh;
      max-height: 100vh;
      border-radius: 0;
    }

    .frigg-modal__header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 20px 24px;
      border-bottom: 1px solid #E5E7EB;
    }

    .frigg-modal__title {
      font-size: 18px;
      font-weight: 600;
      color: #111827;
      margin: 0;
    }

    .frigg-modal__close {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 32px;
      height: 32px;
      padding: 0;
      background: transparent;
      border: none;
      border-radius: 6px;
      color: #6B7280;
      cursor: pointer;
      transition: all 0.2s ease;
    }

    .frigg-modal__close:hover {
      background: #F3F4F6;
      color: #374151;
    }

    .frigg-modal__close svg {
      width: 20px;
      height: 20px;
    }

    .frigg-modal__body {
      flex: 1;
      padding: 24px;
      overflow-y: auto;
    }

    .frigg-modal__footer {
      padding: 16px 24px;
      border-top: 1px solid #E5E7EB;
      display: flex;
      justify-content: flex-end;
      gap: 12px;
    }

    /* Mobile responsive */
    @media (max-width: 640px) {
      .frigg-modal {
        padding: 0;
      }

      .frigg-modal__container {
        max-width: 100%;
        width: 100%;
        height: 100vh;
        max-height: 100vh;
        border-radius: 0;
      }
    }

    /* Dark mode support */
    @media (prefers-color-scheme: dark) {
      .frigg-modal__backdrop {
        background: rgba(0, 0, 0, 0.8);
      }

      .frigg-modal__container {
        background: #1F2937;
      }

      .frigg-modal__header {
        border-bottom-color: #374151;
      }

      .frigg-modal__title {
        color: white;
      }

      .frigg-modal__close {
        color: #9CA3AF;
      }

      .frigg-modal__close:hover {
        background: #374151;
        color: white;
      }

      .frigg-modal__footer {
        border-top-color: #374151;
      }
    }
  `],
  animations: [
    trigger('fadeIn', [
      state('hidden', style({
        opacity: 0
      })),
      state('visible', style({
        opacity: 1
      })),
      transition('hidden => visible', [
        animate('200ms ease-out')
      ]),
      transition('visible => hidden', [
        animate('150ms ease-in')
      ])
    ]),
    trigger('slideUp', [
      state('hidden', style({
        transform: 'translateY(20px) scale(0.95)',
        opacity: 0
      })),
      state('visible', style({
        transform: 'translateY(0) scale(1)',
        opacity: 1
      })),
      transition('hidden => visible', [
        animate('300ms cubic-bezier(0.16, 1, 0.3, 1)')
      ]),
      transition('visible => hidden', [
        animate('200ms cubic-bezier(0.7, 0, 0.84, 0)')
      ])
    ])
  ],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class FriggModalComponent implements OnInit, OnDestroy, AfterViewInit {
  @Input() isOpen: boolean = false;
  @Input() title?: string;
  @Input() size: 'small' | 'medium' | 'large' | 'fullscreen' = 'medium';
  @Input() showCloseButton: boolean = true;
  @Input() showFooter: boolean = false;
  @Input() closeOnEscape: boolean = true;
  @Input() closeOnBackdrop: boolean = true;
  
  @Output() close = new EventEmitter<void>();
  
  @ViewChild('modalContent', { static: false }) modalContent?: ElementRef;

  ngOnInit(): void {
    if (this.closeOnEscape) {
      document.addEventListener('keydown', this.handleEscapeKey);
    }
  }

  ngOnDestroy(): void {
    document.removeEventListener('keydown', this.handleEscapeKey);
  }

  ngAfterViewInit(): void {
    // Focus trap management
    if (this.isOpen && this.modalContent) {
      this.trapFocus();
    }
  }

  handleBackdropClick(event: MouseEvent): void {
    if (this.closeOnBackdrop && event.target === event.currentTarget) {
      this.handleClose();
    }
  }

  handleClose(): void {
    this.close.emit();
  }

  private handleEscapeKey = (event: KeyboardEvent): void => {
    if (event.key === 'Escape' && this.isOpen) {
      this.handleClose();
    }
  };

  private trapFocus(): void {
    // Simple focus trap implementation
    const focusableElements = this.modalContent?.nativeElement.querySelectorAll(
      'a[href], button, textarea, input[type="text"], input[type="radio"], input[type="checkbox"], select'
    );
    
    const firstFocusable = focusableElements?.[0];
    const lastFocusable = focusableElements?.[focusableElements.length - 1];

    if (firstFocusable) {
      (firstFocusable as HTMLElement).focus();
    }

    // Tab cycling logic would go here
  }
}

// packages/ui/vue/src/components/Modal.vue
<template>
  <Teleport to="body">
    <Transition name="modal" @enter="onEnter" @leave="onLeave">
      <div 
        v-if="modelValue" 
        class="modal-overlay" 
        @click="handleOverlayClick"
        :style="{ zIndex }"
      >
        <div 
          :class="['modal', sizeClass, { 'modal-centered': centered }]"
          @click.stop
          ref="modalRef"
        >
          <!-- Header -->
          <div v-if="!hideHeader" class="modal-header">
            <slot name="header">
              <h3 class="modal-title">{{ title }}</h3>
            </slot>
            <button 
              v-if="!hideCloseButton"
              @click="close"
              class="modal-close"
              :aria-label="closeAriaLabel"
            >
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <line x1="18" y1="6" x2="6" y2="18" />
                <line x1="6" y1="6" x2="18" y2="18" />
              </svg>
            </button>
          </div>

          <!-- Body -->
          <div class="modal-body" :style="bodyStyle">
            <slot />
          </div>

          <!-- Footer -->
          <div v-if="!hideFooter && (hasFooterSlot || showDefaultFooter)" class="modal-footer">
            <slot name="footer">
              <button @click="close" class="btn btn-secondary">
                {{ cancelText }}
              </button>
              <button @click="confirm" class="btn btn-primary">
                {{ confirmText }}
              </button>
            </slot>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script>
import { ref, computed, watch, onMounted, onUnmounted, useSlots } from 'vue';

export default {
  name: 'Modal',
  props: {
    modelValue: {
      type: Boolean,
      required: true
    },
    title: {
      type: String,
      default: ''
    },
    size: {
      type: String,
      default: 'medium',
      validator: (value) => ['small', 'medium', 'large', 'xlarge', 'full'].includes(value)
    },
    centered: {
      type: Boolean,
      default: true
    },
    closeOnOverlay: {
      type: Boolean,
      default: true
    },
    closeOnEscape: {
      type: Boolean,
      default: true
    },
    hideHeader: {
      type: Boolean,
      default: false
    },
    hideFooter: {
      type: Boolean,
      default: false
    },
    hideCloseButton: {
      type: Boolean,
      default: false
    },
    showDefaultFooter: {
      type: Boolean,
      default: false
    },
    confirmText: {
      type: String,
      default: 'Confirm'
    },
    cancelText: {
      type: String,
      default: 'Cancel'
    },
    closeAriaLabel: {
      type: String,
      default: 'Close modal'
    },
    bodyStyle: {
      type: Object,
      default: () => ({})
    },
    zIndex: {
      type: Number,
      default: 1000
    },
    trapFocus: {
      type: Boolean,
      default: true
    }
  },
  emits: ['update:modelValue', 'confirm', 'cancel', 'close', 'open'],
  setup(props, { emit }) {
    const modalRef = ref(null);
    const slots = useSlots();
    
    const sizeClass = computed(() => `modal-${props.size}`);
    const hasFooterSlot = computed(() => !!slots.footer);
    
    const close = () => {
      emit('update:modelValue', false);
      emit('close');
    };
    
    const confirm = () => {
      emit('confirm');
      close();
    };
    
    const handleOverlayClick = () => {
      if (props.closeOnOverlay) {
        emit('cancel');
        close();
      }
    };
    
    const handleEscape = (e) => {
      if (e.key === 'Escape' && props.closeOnEscape && props.modelValue) {
        emit('cancel');
        close();
      }
    };
    
    const onEnter = () => {
      document.body.style.overflow = 'hidden';
      emit('open');
      
      if (props.trapFocus) {
        // Focus trap implementation
        setTimeout(() => {
          if (modalRef.value) {
            const focusableElements = modalRef.value.querySelectorAll(
              'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
            );
            if (focusableElements.length > 0) {
              focusableElements[0].focus();
            }
          }
        }, 100);
      }
    };
    
    const onLeave = () => {
      document.body.style.overflow = '';
    };
    
    // Keyboard event listener
    watch(() => props.modelValue, (newVal) => {
      if (newVal) {
        document.addEventListener('keydown', handleEscape);
      } else {
        document.removeEventListener('keydown', handleEscape);
      }
    });
    
    onMounted(() => {
      if (props.modelValue) {
        document.addEventListener('keydown', handleEscape);
      }
    });
    
    onUnmounted(() => {
      document.removeEventListener('keydown', handleEscape);
      document.body.style.overflow = '';
    });
    
    return {
      modalRef,
      sizeClass,
      hasFooterSlot,
      close,
      confirm,
      handleOverlayClick,
      onEnter,
      onLeave
    };
  }
};
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: flex-start;
  justify-content: center;
  padding: 40px;
  overflow-y: auto;
}

.modal {
  background: white;
  border-radius: 8px;
  box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
  display: flex;
  flex-direction: column;
  max-height: calc(100vh - 80px);
  margin: 40px 0;
}

.modal.modal-centered {
  margin: auto 0;
}

/* Size variants */
.modal-small {
  width: 100%;
  max-width: 400px;
}

.modal-medium {
  width: 100%;
  max-width: 600px;
}

.modal-large {
  width: 100%;
  max-width: 800px;
}

.modal-xlarge {
  width: 100%;
  max-width: 1200px;
}

.modal-full {
  width: calc(100vw - 80px);
  max-width: none;
  height: calc(100vh - 80px);
  margin: 0;
}

/* Header */
.modal-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 20px;
  border-bottom: 1px solid #e1e4e8;
}

.modal-title {
  margin: 0;
  font-size: 20px;
  font-weight: 600;
  color: #24292e;
}

.modal-close {
  width: 32px;
  height: 32px;
  padding: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background: transparent;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  color: #586069;
  transition: all 0.2s;
}

.modal-close:hover {
  background: #f0f0f0;
  color: #24292e;
}

.modal-close svg {
  width: 20px;
  height: 20px;
}

/* Body */
.modal-body {
  flex: 1;
  padding: 20px;
  overflow-y: auto;
}

/* Footer */
.modal-footer {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 12px;
  padding: 20px;
  border-top: 1px solid #e1e4e8;
}

/* Buttons */
.btn {
  padding: 8px 20px;
  border: none;
  border-radius: 6px;
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}

.btn-primary {
  background: #007bff;
  color: white;
}

.btn-primary:hover {
  background: #0056b3;
}

.btn-secondary {
  background: #6c757d;
  color: white;
}

.btn-secondary:hover {
  background: #545b62;
}

/* Transitions */
.modal-enter-active,
.modal-leave-active {
  transition: opacity 0.3s ease;
}

.modal-enter-active .modal,
.modal-leave-active .modal {
  transition: all 0.3s ease;
}

.modal-enter-from {
  opacity: 0;
}

.modal-leave-to {
  opacity: 0;
}

.modal-enter-from .modal {
  transform: scale(0.9);
  opacity: 0;
}

.modal-leave-to .modal {
  transform: scale(0.9);
  opacity: 0;
}

/* Responsive */
@media (max-width: 640px) {
  .modal-overlay {
    padding: 20px;
  }
  
  .modal {
    max-height: calc(100vh - 40px);
  }
  
  .modal-full {
    width: calc(100vw - 40px);
    height: calc(100vh - 40px);
  }
}
</style>
