// packages/devtools/management-ui/src/components/ErrorBoundary.jsx
import React from 'react'

class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props)
    this.state = { hasError: false, error: null, errorInfo: null }
  }

  static getDerivedStateFromError(error) {
    // Update state so the next render will show the fallback UI
    return { hasError: true }
  }

  componentDidCatch(error, errorInfo) {
    // Log the error to console or error reporting service
    console.error('ErrorBoundary caught an error:', error, errorInfo)
    this.setState({
      error: error,
      errorInfo: errorInfo
    })
  }

  render() {
    if (this.state.hasError) {
      if (this.props.fallback) {
        return this.props.fallback
      }

      return (
        <div className="min-h-screen bg-gray-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
          <div className="sm:mx-auto sm:w-full sm:max-w-md">
            <div className="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
              <div className="text-center">
                <div className="mx-auto flex items-center justify-center h-12 w-12 rounded-full bg-red-100">
                  <svg className="h-6 w-6 text-red-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.732-.833-2.5 0L3.34 16.5c-.77.833.192 2.5 1.732 2.5z" />
                  </svg>
                </div>
                <h3 className="mt-4 text-lg font-medium text-gray-900">Something went wrong</h3>
                <p className="mt-2 text-sm text-gray-500">
                  An unexpected error occurred. Please refresh the page and try again.
                </p>
                {process.env.NODE_ENV === 'development' && this.state.error && (
                  <details className="mt-4 text-left">
                    <summary className="cursor-pointer text-sm font-medium text-gray-700 hover:text-gray-900">
                      Error details (development only)
                    </summary>
                    <pre className="mt-2 text-xs text-red-600 whitespace-pre-wrap">
                      {this.state.error.toString()}
                      {this.state.errorInfo.componentStack}
                    </pre>
                  </details>
                )}
                <div className="mt-6">
                  <button
                    onClick={() => window.location.reload()}
                    className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                  >
                    Reload page
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )
    }

    return this.props.children
  }
}

export default ErrorBoundary

// packages/ui-svelte/src/components/ErrorBoundary.svelte
<script>
  import { onMount, createEventDispatcher } from 'svelte';
  
  // Props
  export let fallback = null;
  export let onError = null;
  export let resetKeys = [];
  export let resetOnPropsChange = true;
  export let isolate = true;
  
  const dispatch = createEventDispatcher();
  
  // Error state
  let error = null;
  let errorInfo = null;
  let hasError = false;
  
  // Reset error state
  export function resetError() {
    error = null;
    errorInfo = null;
    hasError = false;
  }
  
  // Handle errors
  function handleError(err, info = {}) {
    error = err;
    errorInfo = info;
    hasError = true;
    
    // Call custom error handler
    if (onError) {
      onError(err, info);
    }
    
    // Dispatch error event
    dispatch('error', { error: err, errorInfo: info });
    
    console.error('Error caught by ErrorBoundary:', err);
  }
  
  // Set up error handling
  onMount(() => {
    if (isolate) {
      // In Svelte, we can't catch errors from child components directly
      // But we can listen for unhandled errors
      const handleUnhandledError = (event) => {
        handleError(event.error, {
          componentStack: 'Error caught at boundary',
          errorBoundary: true
        });
        event.preventDefault();
      };
      
      const handleUnhandledRejection = (event) => {
        handleError(event.reason, {
          componentStack: 'Unhandled promise rejection',
          errorBoundary: true
        });
        event.preventDefault();
      };
      
      window.addEventListener('error', handleUnhandledError);
      window.addEventListener('unhandledrejection', handleUnhandledRejection);
      
      return () => {
        window.removeEventListener('error', handleUnhandledError);
        window.removeEventListener('unhandledrejection', handleUnhandledRejection);
      };
    }
  });
  
  // Reset on prop changes
  $: if (resetOnPropsChange && resetKeys.length > 0) {
    resetError();
  }
  
  // Default error UI
  function DefaultErrorFallback({ error, resetError }) {
    return {
      error,
      resetError
    };
  }
</script>

{#if hasError}
  {#if fallback}
    <!-- Custom fallback component -->
    <svelte:component this={fallback} {error} {errorInfo} {resetError} />
  {:else}
    <!-- Default error UI -->
    <div class="error-boundary-default p-6 my-4 bg-red-50 border border-red-200 rounded-lg">
      <div class="flex items-start gap-3">
        <svg class="w-6 h-6 text-red-600 flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        
        <div class="flex-1">
          <h3 class="text-lg font-semibold text-red-900">Something went wrong</h3>
          
          <p class="mt-2 text-sm text-red-700">
            An error occurred while rendering this component.
          </p>
          
          {#if error?.message}
            <div class="mt-3 p-3 bg-red-100 rounded text-xs">
              <p class="font-mono text-red-800">{error.message}</p>
            </div>
          {/if}
          
          <div class="mt-4 flex gap-3">
            <button
              on:click={resetError}
              class="px-4 py-2 bg-red-600 text-white rounded hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 text-sm font-medium"
            >
              Try Again
            </button>
            
            <button
              on:click={() => window.location.reload()}
              class="px-4 py-2 bg-gray-200 text-gray-700 rounded hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm font-medium"
            >
              Reload Page
            </button>
          </div>
          
          {#if errorInfo || (error && error.stack)}
            <details class="mt-4">
              <summary class="cursor-pointer text-sm text-red-700 hover:text-red-800">
                Show error details
              </summary>
              <pre class="mt-2 p-3 bg-red-100 rounded text-xs overflow-x-auto">
{error?.stack || JSON.stringify({ error: error?.toString(), ...errorInfo }, null, 2)}
              </pre>
            </details>
          {/if}
        </div>
      </div>
    </div>
  {/if}
{:else}
  <!-- Normal content -->
  <slot />
{/if}

<style>
  .error-boundary-default {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
  }
  
  pre {
    white-space: pre-wrap;
    word-break: break-word;
  }
</style>
