// packages/ui-vue/src/components/ErrorBoundary.vue
<template>
  <div v-if="hasError" :class="['error-boundary', variantClass]">
    <div class="error-content">
      <div class="error-icon">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <circle cx="12" cy="12" r="10" />
          <line x1="12" y1="8" x2="12" y2="12" />
          <line x1="12" y1="16" x2="12.01" y2="16" />
        </svg>
      </div>
      
      <h3 class="error-title">{{ title || 'Something went wrong' }}</h3>
      
      <p v-if="message || error" class="error-message">
        {{ message || error.message || 'An unexpected error occurred' }}
      </p>
      
      <div v-if="showDetails && error" class="error-details">
        <details>
          <summary>Error Details</summary>
          <pre>{{ errorDetails }}</pre>
        </details>
      </div>
      
      <div class="error-actions">
        <button @click="retry" class="btn-primary">
          {{ retryText || 'Try Again' }}
        </button>
        <button v-if="onReset" @click="reset" class="btn-secondary">
          Reset
        </button>
      </div>
    </div>
  </div>
  <slot v-else />
</template>

<script>
import { ref, computed, onErrorCaptured, watch } from 'vue';

export default {
  name: 'ErrorBoundary',
  props: {
    fallback: {
      type: [String, Object],
      default: null
    },
    onError: {
      type: Function,
      default: null
    },
    onReset: {
      type: Function,
      default: null
    },
    showDetails: {
      type: Boolean,
      default: process.env.NODE_ENV === 'development'
    },
    variant: {
      type: String,
      default: 'default',
      validator: (value) => ['default', 'minimal', 'full'].includes(value)
    },
    title: {
      type: String,
      default: null
    },
    message: {
      type: String,
      default: null
    },
    retryText: {
      type: String,
      default: null
    },
    captureErrors: {
      type: Boolean,
      default: true
    }
  },
  emits: ['error', 'retry', 'reset'],
  setup(props, { emit, slots }) {
    const hasError = ref(false);
    const error = ref(null);
    const errorInfo = ref(null);
    
    const variantClass = computed(() => `variant-${props.variant}`);
    
    const errorDetails = computed(() => {
      if (!error.value) return '';
      
      const details = {
        message: error.value.message,
        stack: error.value.stack,
        ...errorInfo.value
      };
      
      return JSON.stringify(details, null, 2);
    });
    
    // Error capturing
    if (props.captureErrors) {
      onErrorCaptured((err, instance, info) => {
        hasError.value = true;
        error.value = err;
        errorInfo.value = {
          componentName: instance?.$options.name || 'Unknown',
          errorInfo: info
        };
        
        // Call error handler
        if (props.onError) {
          props.onError(err, instance, info);
        }
        
        // Emit error event
        emit('error', { error: err, instance, info });
        
        // Prevent error propagation
        return false;
      });
    }
    
    // Retry functionality
    const retry = () => {
      hasError.value = false;
      error.value = null;
      errorInfo.value = null;
      emit('retry');
    };
    
    // Reset functionality
    const reset = () => {
      hasError.value = false;
      error.value = null;
      errorInfo.value = null;
      
      if (props.onReset) {
        props.onReset();
      }
      
      emit('reset');
    };
    
    // Watch for external error prop changes
    watch(() => props.fallback, (newFallback) => {
      if (newFallback) {
        hasError.value = true;
        if (typeof newFallback === 'object' && newFallback.message) {
          error.value = newFallback;
        }
      }
    }, { immediate: true });
    
    return {
      hasError,
      error,
      errorInfo,
      variantClass,
      errorDetails,
      retry,
      reset
    };
  }
};
</script>

<style scoped>
.error-boundary {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 200px;
  padding: 40px;
}

.error-boundary.variant-minimal {
  min-height: 100px;
  padding: 20px;
}

.error-boundary.variant-full {
  min-height: 400px;
}

.error-content {
  text-align: center;
  max-width: 500px;
}

.error-icon {
  width: 64px;
  height: 64px;
  margin: 0 auto 20px;
  color: #dc3545;
}

.error-boundary.variant-minimal .error-icon {
  width: 32px;
  height: 32px;
  margin-bottom: 12px;
}

.error-icon svg {
  width: 100%;
  height: 100%;
}

.error-title {
  margin: 0 0 12px 0;
  font-size: 24px;
  color: #24292e;
}

.error-boundary.variant-minimal .error-title {
  font-size: 18px;
}

.error-message {
  margin: 0 0 20px 0;
  color: #586069;
  font-size: 16px;
  line-height: 1.5;
}

.error-boundary.variant-minimal .error-message {
  font-size: 14px;
  margin-bottom: 16px;
}

.error-details {
  margin: 20px 0;
  text-align: left;
}

.error-details details {
  background: #f6f8fa;
  border: 1px solid #e1e4e8;
  border-radius: 6px;
  padding: 12px;
}

.error-details summary {
  cursor: pointer;
  font-weight: 600;
  color: #24292e;
  user-select: none;
}

.error-details pre {
  margin: 12px 0 0 0;
  padding: 12px;
  background: #ffffff;
  border: 1px solid #e1e4e8;
  border-radius: 4px;
  font-size: 12px;
  overflow-x: auto;
  white-space: pre-wrap;
  word-break: break-word;
}

.error-actions {
  display: flex;
  gap: 12px;
  justify-content: center;
}

.error-boundary.variant-minimal .error-actions {
  gap: 8px;
}

.error-actions button {
  padding: 8px 20px;
  border: none;
  border-radius: 6px;
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}

.btn-primary {
  background: #007bff;
  color: white;
}

.btn-primary:hover {
  background: #0056b3;
}

.btn-secondary {
  background: #6c757d;
  color: white;
}

.btn-secondary:hover {
  background: #545b62;
}
</style>

// packages/ui-svelte/src/components/ErrorBoundary.svelte
<script>
  import { onMount, createEventDispatcher } from 'svelte';
  
  // Props
  export let fallback = null;
  export let onError = null;
  export let resetKeys = [];
  export let resetOnPropsChange = true;
  export let isolate = true;
  
  const dispatch = createEventDispatcher();
  
  // Error state
  let error = null;
  let errorInfo = null;
  let hasError = false;
  
  // Reset error state
  export function resetError() {
    error = null;
    errorInfo = null;
    hasError = false;
  }
  
  // Handle errors
  function handleError(err, info = {}) {
    error = err;
    errorInfo = info;
    hasError = true;
    
    // Call custom error handler
    if (onError) {
      onError(err, info);
    }
    
    // Dispatch error event
    dispatch('error', { error: err, errorInfo: info });
    
    console.error('Error caught by ErrorBoundary:', err);
  }
  
  // Set up error handling
  onMount(() => {
    if (isolate) {
      // In Svelte, we can't catch errors from child components directly
      // But we can listen for unhandled errors
      const handleUnhandledError = (event) => {
        handleError(event.error, {
          componentStack: 'Error caught at boundary',
          errorBoundary: true
        });
        event.preventDefault();
      };
      
      const handleUnhandledRejection = (event) => {
        handleError(event.reason, {
          componentStack: 'Unhandled promise rejection',
          errorBoundary: true
        });
        event.preventDefault();
      };
      
      window.addEventListener('error', handleUnhandledError);
      window.addEventListener('unhandledrejection', handleUnhandledRejection);
      
      return () => {
        window.removeEventListener('error', handleUnhandledError);
        window.removeEventListener('unhandledrejection', handleUnhandledRejection);
      };
    }
  });
  
  // Reset on prop changes
  $: if (resetOnPropsChange && resetKeys.length > 0) {
    resetError();
  }
  
  // Default error UI
  function DefaultErrorFallback({ error, resetError }) {
    return {
      error,
      resetError
    };
  }
</script>

{#if hasError}
  {#if fallback}
    <!-- Custom fallback component -->
    <svelte:component this={fallback} {error} {errorInfo} {resetError} />
  {:else}
    <!-- Default error UI -->
    <div class="error-boundary-default p-6 my-4 bg-red-50 border border-red-200 rounded-lg">
      <div class="flex items-start gap-3">
        <svg class="w-6 h-6 text-red-600 flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        
        <div class="flex-1">
          <h3 class="text-lg font-semibold text-red-900">Something went wrong</h3>
          
          <p class="mt-2 text-sm text-red-700">
            An error occurred while rendering this component.
          </p>
          
          {#if error?.message}
            <div class="mt-3 p-3 bg-red-100 rounded text-xs">
              <p class="font-mono text-red-800">{error.message}</p>
            </div>
          {/if}
          
          <div class="mt-4 flex gap-3">
            <button
              on:click={resetError}
              class="px-4 py-2 bg-red-600 text-white rounded hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 text-sm font-medium"
            >
              Try Again
            </button>
            
            <button
              on:click={() => window.location.reload()}
              class="px-4 py-2 bg-gray-200 text-gray-700 rounded hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-500 text-sm font-medium"
            >
              Reload Page
            </button>
          </div>
          
          {#if errorInfo || (error && error.stack)}
            <details class="mt-4">
              <summary class="cursor-pointer text-sm text-red-700 hover:text-red-800">
                Show error details
              </summary>
              <pre class="mt-2 p-3 bg-red-100 rounded text-xs overflow-x-auto">
{error?.stack || JSON.stringify({ error: error?.toString(), ...errorInfo }, null, 2)}
              </pre>
            </details>
          {/if}
        </div>
      </div>
    </div>
  {/if}
{:else}
  <!-- Normal content -->
  <slot />
{/if}

<style>
  .error-boundary-default {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
  }
  
  pre {
    white-space: pre-wrap;
    word-break: break-word;
  }
</style>
